DB_GROUP = "Dogbone"
DB_NAME = "dogbone"

COMMAND_ID = "dogboneBtn"
UPD_COMMAND_ID = "dogboneUpdateBtn"

ACUTE_ANGLE = "acuteAngle"
ANGLE_DETECTION_GROUP = "angleDetectionGroup"
BENCHMARK = "benchmark"
DEPTH_EXTENT = "depthExtent"
DOGBONE_TYPE = "dogboneType"
EDGE_SELECT = "edgeSelect"
FACE_SELECT = "faceSelect"
FROM_SELECTED_FACE = "From Selected Face"
FROM_TOP_FACE = "From Top Face"
LOGGING = "logging"
MAX_SLIDER = "maxSlider"
MINIMAL_DOGBONE = "Minimal Dogbone"
MINIMAL_PERCENT = "minimalPercent"
MIN_SLIDER = "minSlider"
MODE_GROUP = "modeGroup"
MODE_ROW = "modeRow"
MORTISE_DOGBONE = "Mortise Dogbone"
MORTISE_TYPE = "mortiseType"
NORMAL_DOGBONE = "Normal Dogbone"
OBTUSE_ANGLE = "obtuseAngle"
ON_LONG_SIDE = "On Long Side"
ON_SHORT_SIDE = "On Short Side"
PARAMETRIC = "Parametric"
PREVIEW_ENABLE = "PreviewEnable"
SETTINGS_GROUP = "settingsGroup"
STATIC = "Static"
TOOL_DIAMETER = "toolDia"
TOOL_DIAMETER_OFFSET = "toolDiaOffset"

EDGE_TOOLTIP = "click to SELECT OR de-SELECT an internal edge"
FACE_TOOLTIP = "click a face to select"

# fix: 선택 게이트 제거로 일반 클릭 선택이 가능해져 Ctrl-click 안내 문구를 실제 동작과 일치시킴
EDGE_TOOLTIP_PREVIEW = "click to SELECT OR de-SELECT an internal edge"
FACE_TOOLTIP_PREVIEW = "click a face to select"

EDGE_TOOLTIP_DESCRIPTION = "Only valid dogbone edges can be selected"
FACE_TOOLTIP_DESCRIPTION = ("applies dogbones to all corner edges dropping from face"
                                    "\n*** Select faces by clicking on them. DO NOT DRAG SELECT! ***")